//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.DataAccess.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Zimmet = new HashSet<Zimmet>();
        }
    
        public int PersonalId { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public long KisiId { get; set; }
        public int BolumId { get; set; }
        public int Sifre { get; set; }
        public string Mail { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        public virtual Kisi Kisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zimmet> Zimmet { get; set; }
    }
}
