//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.DataAccess.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zimmet
    {
        public int ZimmetId { get; set; }
        public int ZimmetAded { get; set; }
        public int ZimmetDurumu { get; set; }
        public int UrunId { get; set; }
        public int MarkaId { get; set; }
        public int PersonalId { get; set; }
    
        public virtual Atik Atik { get; set; }
        public virtual Marka Marka { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
